CREATE TABLE IF NOT EXISTS covers (
    id          INTEGER PRIMARY KEY        NOT NULL,
    image_url   TEXT                    NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id          INTEGER PRIMARY KEY        NOT NULL,
    name        TEXT                    NOT NULL,
    summary     TEXT                    NOT NULL,
    first_release_date INTEGER,
    cover_id    INTEGER 
);

CREATE TABLE IF NOT EXISTS releases (
    id          INTEGER PRIMARY KEY      NOT NULL,
    release_date INTEGER,
    product_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    platform INTEGER NOT NULL,
    release_status INTEGER,
    release_region INTEGER
);

CREATE TABLE IF NOT EXISTS platforms (
    id INTEGER PRIMARY KEY NOT NULL,
    abbreviation TEXT,
    name TEXT NOT NULL,
    generation INTEGER
);

CREATE TABLE IF NOT EXISTS regions (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL 
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    user_login TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users_have_releases (
    release_id  INTEGER REFERENCES releases(id) ON DELETE CASCADE NOT NULL,
    user_login  TEXT REFERENCES users(user_login) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (release_id, user_login)
);

CREATE TABLE IF NOT EXISTS screenshots (
    id          INTEGER PRIMARY KEY        NOT NULL,
    image_url   TEXT                    NOT NULL,
    game INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS product_platforms (
    product_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    platform_id INTEGER REFERENCES platforms(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (product_id, platform_id)
);

CREATE TABLE IF NOT EXISTS users_have_wishes (
    release_id  INTEGER REFERENCES releases(id) ON DELETE CASCADE NOT NULL,
    user_login  TEXT REFERENCES users(user_login) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (release_id, user_login)
);

CREATE TABLE IF NOT EXISTS users_have_bids (
    release_id  INTEGER REFERENCES releases(id) ON DELETE CASCADE NOT NULL,
    user_login  TEXT REFERENCES users(user_login) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (release_id, user_login)
);

ALTER TABLE platforms
  ADD COLUMN IF NOT EXISTS "active" BOOLEAN DEFAULT FALSE;

ALTER TABLE platforms
  ADD COLUMN IF NOT EXISTS "total_games" INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    sender_login TEXT NOT NULL REFERENCES users(user_login),
    recipient_login TEXT NOT NULL REFERENCES users(user_login),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_messages_recipient ON messages (recipient_login);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages (sender_login);
