global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:9090']
    basic_auth:
      username: admin
      password: ${PROMETHEUS_PASSWORD}
